### PR TITLE
buff cooldowns

### PR DESCRIPTION
**Pull request by sipertruk**
#120

### CODE REVIEW

**Comment by Aviana** [comment]
I will review this during the weekend.

**Comment by Aviana** [comment]
Ok here is my feedback:

- Don't make the bufftime db character based. Buff times will always be the same except for buffs that have it modified by setbonuses or talents but even then it won't be bad to have a longer duration stored in your database. It will simply show the cooldown spirals as more progressed even though the buff was just applied. Also math.ceil() the value when you write it to the db as times are always a bit progressed instead of showing the real duration (you will get 3.9455354 instead of 4 for example).
- The setting of the spiral and the handling of the bufftimer db has to be in the buffupdate function instead of the onupdate. It is only necessary to set those once buffs are applied or removed. Also never ever do this in an onupdate:
`LunaBuffDB[LunaBuffDBPlayerString] = {}`
This will create a new chunk in memory every frame, leaving the old one there for the garbage collector to pick up. The more the garbage collector has to run the worse your game performance gets.
- You could also re-use the tooltip object that is stored in the global "LunaUnitFrames" instead of creating another local one but its not that big of a deal i guess.

**Comment by sipertruk** [comment]
I agree on everything except I prefer the character based "volatile" db for the following reasons.

- Spell ranks also modify the durations particularly for debuffs like dot, the biggest difference happening for control debuff, example polymorphism rank 1 20s to rank 4 50s. As a result for rank 1 you would see the animation start at more than half of the course.
- It would keep the setting file short instead of maintaining a database of all the buff durations in the game.
- Isn't there in the game a boss ability that creates a buff much longer than a player one but with the same name ? If it is the case or if in any way a wrong value goes into the db it would stay until the user get rid of it manually.
- It comes at little cost all considered, I replaced the drop of memory by a loop wipe of the table, plus it happens only on buffFrameUpdate, only for the "player" frame.

**Comment by sipertruk** [comment]
That latest commit was pushed too fast, I'll rethink that.

**Comment by sipertruk** [comment]
I forgot to move CooldownFrame_SetTimer, correctly copy the db and reuse the copied table.

**Comment by sipertruk** [comment]
So I remember now why I put CooldownFrame_SetTimer into OnUpdate : when an already applied buff is applied again And the buffs stay in the same order neither UNIT_AURA or PLAYER_AURAS_CHANGED is triggered.
Or maybe I'm missing something ?

**Comment by Aviana** [comment]
Even though you make your buff db character based don't copy the entire database. Just check if the time remaining on a buff is greater than what you have in the database and if it is store the new value.

**Comment by sipertruk** [comment]
Just committed a version without db copy and therefore no copy wiping.
It uses a (re-usable) table and the actual time of the event to store the current buffs and then it wipes selectively the database at the end.

**Pull request merged**
