### PR TITLE
LUA Error Fix

### PR DESCRIPTION
**Pull request by HelloKitty**
This fixes a LUA error that occurs when modifying options for castbars.

### CODE REVIEW

**Comment by HelloKitty** [comment]
I've never worked with WoW addons nor have I written any LUA but I hope this can help fix a bug I believe is present.

**Comment by Aviana** [comment]
This would override the setting of the fontsize of the castbar, making it a static size. I know about the error but wasn't able to reproduce it. Please post your settings or what you did when it happened.

**Comment by jazzlyn** [comment]
Hey Aviana,

I reproduced it a few times. I changed the following settings:

* Player Frame has castbar deactivated.
* Target Frame has castbar with font size 1, other settings default.
* ToT has only health frame

I get the following LUA error:
\modules\Player.lua:994:<unnamed>:SetText(): Font not set

My situation:

* It doesn't matter if its infight or out of fight.

* when I change the font size of the Target Frame and cast for example Minor Mana Oil on my weapon, the error pops up. It occurs now every time I cast something till I reload UI. After reload the changed font size is displayed correct and no error. But if I open the Target Frame settings again and drop down to castbar settings (without changing anything!) I'll get the error again...

* maybe important: that error occurs only with the Target Frame castbar, not with Player Frame.

Besides: The Target castbar works only for enemies, not for friendly targets.

I hope this helps a bit.

Bye

**Comment by Aviana** [comment]
fixed.

**Pull request closed without merging**
